[project]
name = "sturdy-lp-miner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.11"
dependencies = [
    "sturdy-subnet",
]

[tool.uv.sources]
sturdy-subnet = { git = "https://github.com/Sturdy-Subnet/sturdy-subnet", rev = "feat/sturdy-lp-miner-whitelist" }
