[project]
name = "distributor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.11"
dependencies = [
    "aiosqlite>=0.21.0",
    "argparse>=1.4.0",
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "loguru>=0.7.0",
    "matplotlib>=3.10.3",
    "ruff>=0.12.4",
    "sturdy-subnet",
]

[tool.uv.sources]
sturdy-subnet = { git = "https://github.com/Sturdy-Subnet/sturdy-subnet", rev = "4.0.12" }
